Feat/login page backend
HackMerced/HackMerced pull request #124
Opened 2020-10-13 07:27 UTC by trumanjchan

# Proposed changes

Adrian helped me with the backend of the login page form (email and password). It works as it should. I then attempted to make a Modal for the "Forgot Password?' button. I ended up using @shiv248 's Modal from his Title component. I wasn't able to make it work, so what it does right now is if you click on the 'Forgot Password?' button, the Modal pops up and you can input an email and submit. However you cannot exit the Modal without manually refreshing the page or clicking another HackMerced Hub page. As for the 'Create an Account' button, the sign-up page needs to be finished so this button can link to that page.

## Types of changes

What types of changes does your code introduce to HackMerced Hub?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/HackMerced/HackMerced/blob/master/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

## Responsiveness

Check off the different **browsers** and **devices** you have tested on.

### Browsers

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari

### Devices

- [x] Windows
- [ ] MacOSX
- [ ] Linux
- [ ] IPhone
- [ ] Android
- [ ] Tablet

## Screenshots

![image](https://user-images.githubusercontent.com/43284404/95828384-c8295f80-0ce9-11eb-909e-271aa765b8f8.png)

![image](https://user-images.githubusercontent.com/43284404/95828187-83052d80-0ce9-11eb-95ff-864a3ccf96f7.png)

You can see on the right side that submitting the form (email and password) sends the correct Axios ping. However submitting the Modal form (email) doesn't seem to be correct. Someone with better backend experience should look over my code.

## Further comments

Maybe we shouldn't have a Modal?

2020-10-13 19:35 UTC, maryharebear commented
Hi @trumanjchan! great work on connecting the login page with backend, so now we can test it! The modal on the title of the hub was created by @adriandarian, and there's still a bug that's occurring there when we clicked on the form, it immediately exits out of the form. You can test this bug on the live site. I would say for the forgot password one, you can continue with this modal and have a style for it while looking around other's forgot password. You can also add a go back button that links back to the login page. When you are adding a forgot password function, it needs to send the users an email of how to change their password, you can get help on this from @BusherBridi and @adriandarian. 

Also, for Plan B if the modal does not work at all you can try adding a page instead and styling that.

2020-10-20 22:09 UTC, trumanjchan commented
I believe most of this task is done. I need someone to look at the backend work though. Please refer to the bottom paragraph of this PR (under the screenshot).

2020-10-22 23:09 UTC, adriandarian requested changes

2020-10-22 23:09 UTC, adriandarian commented on src/pages/Login-ResetPassword/login-resetpassword.tsx
> +        event: React.ChangeEvent<HTMLInputElement> | React.ChangeEvent<HTMLSelectElement>,
```suggestion
        event: React.ChangeEvent<HTMLInputElement>,
```

Remove since you are not using a select form option

2020-10-22 23:09 UTC, adriandarian commented on src/pages/Login-ResetPassword/login-resetpassword.tsx
> +            </main>
```suggestion
            <section className="reset-page">
                <div className="center-container">
                    <img className="logo" src={Hackmercedlogo} alt="Logo" height={120} width={120} />
                    <h1>Reset Password</h1>
                    <form onSubmit={handleSubmit} className="form-container">
                        <input onChange={handleInputChange} className="emailinput" type="email" placeholder="Email" id="email" name="email" />
                        <FontAwesomeIcon icon={faUser} className="blackicon" />
                        <input className="submitbutton" type="submit" value="Submit" />
                    </form>
                </div>
            </section>
```

2020-10-22 23:09 UTC, adriandarian commented on src/pages/Login-ResetPassword/login-resetpassword.tsx
> +                    <img className="logo" src={Hackmercedlogo} alt="Logo" height={120} width={120} />
```suggestion
                    <img className="logo" src={Hackmercedlogo} alt="Logo" />
```

The width and height for images should be in the SCSS files.

2020-10-22 23:29 UTC, maryharebear commented
Hi @trumanjchan, please look at your mobile view, just make the form longer so it fits the site instead of having white blanks
![image](https://user-images.githubusercontent.com/55856581/96940127-ba12d600-1483-11eb-8e7a-cc4e905dd327.png)

2020-10-23 19:47 UTC, trumanjchan commented
@maryharebear the issue is fixed.

2020-10-24 01:12 UTC, maryharebear approved these changes

2020-10-24 01:14 UTC, merged