Created LHD Schedule Component
HackMerced/HackMerced pull request #191
Opened 2021-10-08 09:08 UTC by Abdus-Samee

Added the tsx and scss file under the components folder

# Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to HackMerced Hub?
_Put an `x` in the boxes that apply_

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

-   [x] I have read the [CONTRIBUTING](https://github.com/HackMerced/HackMerced/blob/master/CONTRIBUTING.md) doc
-   [ ] Lint and unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)
-   [ ] Any dependent changes have been merged and published in downstream modules

## Responsiveness

Check off the different **browsers** and **devices** you have tested on. Note: testing includes Horizontal and Vertical alignments

### Browsers

-   [x] Chrome
-   [x] Firefox
-   [x] Edge
-   [ ] Safari
-   [ ] Brave
-   [ ] Opera

### Devices

#### Phones

-   [x] Moto G4
-   [x] Galaxy S5
-   [x] Pixel 2
-   [x] Pixel 2 XL
-   [x] iPhone 5/SE
-   [x] iPhone 6/7/8
-   [x] iPhone 6/7/8 Plus
-   [x] iPhone X

#### Tablets

-   [x] iPad
-   [x] iPad Pro

#### Desktops

-   [x] Windows 10
-   [ ] MacOSX
-   [ ] Ubuntu

## Screenshots

_Please attach at least one Desktop and Mobile screenshot of your update._
![desktop](https://user-images.githubusercontent.com/53638835/137158896-79b9fdbf-2e59-420e-85c7-f8eae5557373.png)
![mobile](https://user-images.githubusercontent.com/53638835/137158905-da8e9cc6-6d22-4fc9-bea1-f95550404006.png)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2021-10-13 21:37 UTC, maryharebear requested changes
Hi @Abdus-Samee Great Job!! I love that it's responsive and look like the mockup design. Now let's just put the content from our itinerary schedule link [here](https://docs.google.com/spreadsheets/d/1Q1n0b34c9hSFqd-c3v7EUFF5qNy-HwL_kSm3zt3m9W0/edit?usp=sharing ). And add one more feature which is a hover text box to put in the location of the events and description that looks like this 
![image](https://user-images.githubusercontent.com/55856581/137216099-ccacdee8-7477-4417-978a-c4b989b60ccb.png)

2021-10-14 11:41 UTC, Abdus-Samee commented
Hello @maryharebear . I've added the hover textbox which is responsive too. An image from the mobile view:
![mob](https://user-images.githubusercontent.com/53638835/137310768-4ff92eca-39b8-491c-a0cd-9e60999ea3e2.PNG)

2021-10-18 06:06 UTC, maryharebear approved these changes

2021-10-18 06:06 UTC, maryharebear commented
Great job!! @Abdus-Samee love your pr :)

2021-10-18 06:07 UTC, merged